import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "@/app/globals.css";
import { Providers } from "@/app/providers";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ChrisTalk",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${roboto.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="bg-background text-foreground min-h-screen h-full flex flex-col m-2">
        <Providers>
          <div className="flex flex-col gap-2 w-full h-full">
            <div className="flex-1 w-full h-full justify-center items-center">
              {children}
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
